import * as EventEmitter from 'events'


 

export const eventTypes = {
    WORKSPACE_CREATED: 'WORKSPACE_CREATED',
    WORKSPACE_RUD: 'WORKSPACE_RUD',
    WORKSPACE_ERR: 'WORKSPACE_ERR',
    DEPLOYMENT_CRUD: 'DEPLOYMENT_CRUD',
    DEPLOYMENT_ERR: 'DEPLOYMENT_ERR',
    WIKI_CRUD: 'WIKI_CRUD',
    WIKI_ERR: 'WIKI_CRUD',
    USER_CRUD: 'USER_CRUD',
    USER_ERR: 'USER_ERR',
    PROJECT_CRUD: 'PROJECT_CRUD',
    PROJECT_ERR: 'PROJECT_ERR',
    PROJECT_LANE_CRUD: 'PROJECT_LANE_CRUD',
    PROJECT_LANE_ERR: 'PROJECT_LANE_ERR',
    LANE_TASKS_CRUD: 'LANE_TASKS_CRUD',
    LANE_TASK_MOVED: 'LANE_TASK_MOVED',
    LANE_TASKS_ERR: 'LANE_TASKS_ERR'
    
}

export const events = new EventEmitter()
